version: '3'

services:
  tests:
    image: travisci/ci-minimal
    build:
      context: .
      dockerfile: .dockerfile
    command: >
      bash .travis_all.sh
    volumes:
      - .:/home/travis/ll
    privileged: true
    stdin_open: true
    tty: true
