dist: trusty
sudo: false 

language: c

cache:
  timeout: 1000
  directories:
    - $HOME/.asdf

before_install: >-
  if [ -d $HOME/.asdf ]; then
    echo "asdf found, skipping install"
    echo -e '\n. $HOME/.asdf/asdf.sh' >> $HOME/.bashrc
    echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> $HOME/.bashrc
    source ~/.bashrc
  else
    sudo apt-get update
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.4.3
    echo -e '\n. $HOME/.asdf/asdf.sh' >> $HOME/.bashrc
    echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> $HOME/.bashrc
    source $HOME/.bashrc
    asdf plugin-add nim https://github.com/rfrancis/asdf-nim
    asdf install nim v0.18.0
  fi
  asdf global nim v0.18.0

jobs:
  include:
    - stage: run tests
      script: nimble build && nimble test
