language: c

cache:
  timeout: 1000
  directories:
    - $HOME/.asdf

before_install:
  - sudo apt-get update
  - [ ! -d ~/.asdf ] && git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.3
  - echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
  - source ~/.bashrc
  - asdf plugin-add nim https://github.com/rfrancis/asdf-nim
  - asdf install nim v0.18.0
  - asdf global nim v0.18.0

jobs:
  include:
    - stage: run tests
      script: nimble build && nimble test
